function(print_variables)
    message(STATUS "The CMake Source directory is ${CMAKE_SOURCE_DIR}")
    message(STATUS "The CMake binary directory is ${CMAKE_BINARY_DIR}")
    message(STATUS "The Source directory of the '${PROJECT_NAME}' project is  ${PROJECT_SOURCE_DIR}")
    message(STATUS "The Binary directory of the '${PROJECT_NAME}' project is  ${PROJECT_BINARY_DIR}")
    message(STATUS "The version of the current project is ${PROJECT_VERSION}")
    message(STATUS "The current Source directory is  ${CMAKE_CURRENT_SOURCE_DIR}")
    message(STATUS "The current Binary directory is  ${CMAKE_CURRENT_BINARY_DIR}")
    message(STATUS "The current script file is ${CMAKE_CURRENT_LIST_FILE}")
    message(STATUS "The current script directory is ${CMAKE_CURRENT_LIST_DIR}")
endfunction()